baseurl: "/lynxblog"
domain: ""
url: "https://clyron.is-a.dev"
name: "Lynxmic Blog"
logo: "/img/wordmark.svg"
favicon: "/img/logotype.png"
image_src: "/img/postmedia/"
rss: "feed.xml"
paginate: 10
paginate_path: "/:num/"
page_excerpts: true
timezone: Europe/Bucharest
currentyear: "2024"

author: Lynxmic
source_url: "https://github.com/theclyron/lynxblog"

plugins:
  - jekyll-feed
  - jekyll-paginate
